"use client";

import { motion, useReducedMotion } from "motion/react";
import { FeatureCard } from "@/components/ui/grid-feature-cards";
import {
    Sparkles,
    Target,
    MessageCircle,
    Brain,
    Shield,
    BarChart3,
} from "lucide-react";

const features = [
    {
        title: "AI Career Roadmap",
        icon: Sparkles,
        description:
            "Get a personalized, step-by-step career roadmap generated by AI based on your resume's skill gaps and target role.",
    },
    {
        title: "ATS JD Matcher",
        icon: Target,
        description:
            "Paste any job description and instantly see your ATS match score, missing keywords, and actionable suggestions to improve.",
    },
    {
        title: "Chat with Your Resume",
        icon: MessageCircle,
        description:
            "An interactive AI chat that answers any question about your resume — strengths, weaknesses, career advice, and more.",
    },
    {
        title: "AI-Powered Role Prediction",
        icon: Brain,
        description:
            "Groq's LLM deeply analyzes your resume to predict the top 3 career roles you're best suited for with confidence scores.",
    },
    {
        title: "Confidence Analytics",
        icon: BarChart3,
        description:
            "Beautiful interactive charts breaking down your role match confidence, skill distribution, and career fit analysis.",
    },
    {
        title: "Secure & Rate-Limited",
        icon: Shield,
        description:
            "Protected by Clerk authentication and Upstash Redis rate limiting. Your data is stored securely in a PostgreSQL database.",
    },
];

type ViewAnimationProps = {
    delay?: number;
    className?: React.ComponentProps<typeof motion.div>["className"];
    children: React.ReactNode;
};

function AnimatedContainer({
    className,
    delay = 0.1,
    children,
}: ViewAnimationProps) {
    const shouldReduceMotion = useReducedMotion();

    if (shouldReduceMotion) {
        return <div className={className}>{children}</div>;
    }

    return (
        <motion.div
            initial={{ filter: "blur(4px)", translateY: -8, opacity: 0 }}
            whileInView={{ filter: "blur(0px)", translateY: 0, opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay, duration: 0.8 }}
            className={className}
        >
            {children}
        </motion.div>
    );
}

export default function Features() {
    return (
        <section id="features" className="py-16 md:py-32 bg-[#020202]">
            <div className="mx-auto w-full max-w-5xl space-y-8 px-4">
                <AnimatedContainer className="mx-auto max-w-3xl text-center">
                    <h2 className="text-3xl font-bold tracking-wide text-balance md:text-4xl lg:text-5xl xl:font-extrabold text-white">
                        Everything you need to land your dream role
                    </h2>
                    <p className="text-white/50 mt-4 text-sm tracking-wide text-balance md:text-base">
                        4 powerful AI-powered features that analyze your resume, match you to jobs,
                        generate career roadmaps, and let you chat with your own resume.
                    </p>
                </AnimatedContainer>

                <AnimatedContainer
                    delay={0.4}
                    className="grid grid-cols-1 divide-x divide-y divide-white/10 border border-white/10 sm:grid-cols-2 md:grid-cols-3"
                >
                    {features.map((feature, i) => (
                        <FeatureCard key={i} feature={feature} />
                    ))}
                </AnimatedContainer>
            </div>
        </section>
    );
}
