import { NextRequest, NextResponse } from "next/server";
import { jsPDF } from "jspdf";

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { roles, skills, experienceLevel, summary } = body;

        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();

        // Header
        doc.setFillColor(15, 23, 42); // Dark navy
        doc.rect(0, 0, pageWidth, 45, "F");

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text("AI Resume Screening Report", pageWidth / 2, 20, { align: "center" });

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.text(`Generated on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, pageWidth / 2, 32, { align: "center" });

        // Summary section
        let y = 60;
        doc.setTextColor(15, 23, 42);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Profile Summary", 20, y);
        y += 10;
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(71, 85, 105);

        const summaryLines = doc.splitTextToSize(summary || "No summary available.", pageWidth - 40);
        doc.text(summaryLines, 20, y);
        y += summaryLines.length * 6 + 5;

        doc.setTextColor(15, 23, 42);
        doc.setFontSize(10);
        doc.text(`Experience Level: ${experienceLevel || "Not specified"}`, 20, y);
        y += 15;

        // Top Roles
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(15, 23, 42);
        doc.text("Top Role Predictions", 20, y);
        y += 10;

        if (roles && Array.isArray(roles)) {
            roles.forEach((role: { name: string; confidence: number; reason: string }, index: number) => {
                // Role box
                doc.setFillColor(248, 250, 252);
                doc.roundedRect(20, y - 4, pageWidth - 40, 28, 3, 3, "F");

                doc.setFontSize(12);
                doc.setFont("helvetica", "bold");
                doc.setTextColor(15, 23, 42);
                doc.text(`${index + 1}. ${role.name}`, 25, y + 4);

                // Confidence badge
                const confColor = role.confidence >= 70 ? [34, 197, 94] : role.confidence >= 50 ? [251, 191, 36] : [239, 68, 68];
                doc.setTextColor(confColor[0], confColor[1], confColor[2]);
                doc.setFontSize(11);
                doc.setFont("helvetica", "bold");
                doc.text(`${role.confidence}%`, pageWidth - 30, y + 4, { align: "right" });

                doc.setFontSize(9);
                doc.setFont("helvetica", "normal");
                doc.setTextColor(100, 116, 139);
                const reasonLines = doc.splitTextToSize(role.reason, pageWidth - 50);
                doc.text(reasonLines, 25, y + 14);

                y += 35;
            });
        }

        // Skills
        y += 5;
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(15, 23, 42);
        doc.text("Key Skills Identified", 20, y);
        y += 10;

        if (skills && Array.isArray(skills)) {
            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(71, 85, 105);
            const skillsText = skills.join("  •  ");
            const skillLines = doc.splitTextToSize(skillsText, pageWidth - 40);
            doc.text(skillLines, 20, y);
        }

        // Footer
        const pageHeight = doc.internal.pageSize.getHeight();
        doc.setFillColor(248, 250, 252);
        doc.rect(0, pageHeight - 20, pageWidth, 20, "F");
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text("Generated by ResumeAI — AI Resume Screener", pageWidth / 2, pageHeight - 8, { align: "center" });

        // Generate buffer
        const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

        return new NextResponse(pdfBuffer, {
            headers: {
                "Content-Type": "application/pdf",
                "Content-Disposition": 'attachment; filename="resume_analysis_report.pdf"',
            },
        });
    } catch (error) {
        console.error("Report generation error:", error);
        return NextResponse.json(
            { error: "Failed to generate report" },
            { status: 500 }
        );
    }
}
